### ISSUE TITLE
Thoughts

### ISSUE THREAD

**Issue by virtuald** [Team4819/Yeti#1]
Disclaimer: I've only read your documentation, and haven't actually read the code yet

The LittleRobot example is very strange to me. It seems like _every_ yeti program will look exactly like that, right? Why not bundle it in the framework and tell users that their robot.py must look like this?

```
import wpilib
import yeti.robots

if __name__ == '__main__':
    wpilib.run(yeti.robots.StandardRobot)
```

The teleop loop in your example module is also strange. Since, it's a while True, it never returns -- even when not in teleop mode. This makes it harder to reinitialize teleop mode variables if you're doing something more complex, because it's harder to determine when we re-entered it. I think instead of using the gamemode.wait_for_teleop(), I would probably do something like... 

```
def teleop_loop(self, loop):
    while (yield from loop):
        ... 
```

The fact that you have to call the teleop_loop from your module is strange too, why not use a decorator or some standard function that gets called, and have the framework call that function automatically. Less boilerplate.

The WebUI looks neat.

**Comment by computer-whisperer** [comment]
I have implemented all of your suggestions -- thanks!
